spring:
  application:
    name: vcmail-app
  datasource:
    url: jdbc:postgresql://vcmail-db:5432/vcmailDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080


assemblyai:
  api:
    key: YOK